# Save the toggled spawns to a file to load after server restart.
# If this false, if the file is exists, it will be deleted automatically at server restart.
remember-toggled-spawns-to-file: true

# How many seconds have to wait for a player to be teleported?
# If 0, will instantly teleports.
# This will be ignored with "setthespawn.bypass.cooldown" permission for specific players
teleport-delay: 0

# This allows to send the messages repeatedly when the player starts
# teleporting, or if it is false, sends the message once only.
teleport-message-repeater: false

# Teleport progress bar while the player started teleport.
progress-bar:
  enable: false

  # Progress bar size
  bar-size: 30.0

  # Bar update fast in ticks.
  fast: 2

  # Teleport progress display mark.
  mark: "\u258B"

  # When the teleport is ready.
  done-color: "&a&l"

  # When teleport is not ready yet.
  not-done-color: "&c&l"

  # Use %output%, %time% placeholder.
  message-format: "&aTeleporting in:&7&l [%output%&7&l]&6 (&8%time%&6)"

# If the spawn can not be found, teleport it to the world spawn?
teleport-to-world-spawn-if-spawn-not-found: false

# Teleport the player to the default set world spawn?
# If this true, ignores the spawn locations, join spawn that has been set and teleports
# to the world spawn location.
#teleport-to-world-spawn: false

# Teleport to the set player bed spawn. If the player bed spawn not found,
# will teleporting to the spawn.
# The bed location not handled by this plugin!
#teleport-to-bed-spawn: false

# Do include operator players in teleporting to teleport them?
# This happens when a player teleports everyone.
teleport-op-players: false

# A player teleported to the spawn, how many seconds to protect the player from damage?
# Set 0 to disable.
no-damage-time: 0

# Teleports automatically to spawn, when a player afk status is true.
# Requires Essentials!
auto-teleport-to-spawn-when-player-afk: false

# Use separate worlds?
# If enabled, will changes the spawn behavior when the players teleporting.
# So if this true then the players will be teleported to the spawn where the player is in that world.
# This will changes the spawn settings in the spawns file.
per-world-spawn: false

# In which worlds can spawn not be set and used?
disabled-worlds:
#- world_the_end

# Prevent spawn command executing when a player in pvp.
disable-spawn-in-pvp:
  enable: false

  # Command re-allow time in seconds.
  time: 5

  # Message when you attack a player or attack you.
  message: "&cNow you can not teleport to spawn because you're still fighting with a player."

# Check if the player is in flying mode?
# If it is true, players can teleport while flying.
# If it is false, it will cancel the teleport delay.
# This ignores with setthespawn.bypass.fly permission.
allow-spawn-when-flying: true

# Allows to the player to teleport to the spawn if the player is in minecart.
# This can be bypassed with setthespawn.bypass.minecart permission.
allow-spawn-when-is-in-minecart: true

# Allows to the player to teleport to the spawn if the player is in boat.
# This can be bypassed with setthespawn.bypass.boat permission.
allow-spawn-when-is-in-boat: true

# Prevent spawn teleport when player is in fire?
# This ignores with setthespawn.bypass.fire permission.
prevent-spawn-when-player-is-in-fire: false

# When a player presses the SHIFT button while teleporting, and sits in snake mode,
# will it cancel the teleportation?
# This ignores with setthespawn.bypass.sneak permission.
check-sneak-while-teleport:
  enable: false
  message: "&cTeleporting is canceled because snake mode is enabled."

# Cost for /spawn command executing or sign interacting.
# For this, requires the Vault plugin.
spawn-cost:
  # If this is given at the group, they can use the /spawn command without payment.
  # If not given, the /spawn command must be paid.
  # This will be ignored if this empty.
  permission: setthespawn.bypass.spawncost

  # This can be set as per-spawn when setting the spawn point.
  cost: 0.0

  # Sign usage price (Same as /spawn command)
  sign:
    # If this is given at the group, they can use the spawn sign without payment.
    # If not given, the spawn sign usage must be paid.
    # This will be ignored if this empty.
    permission: setthespawn.bypass.signcost

    # Cost of sign usage
    cost: 0.0

# Cancel teleport if:
cancel-teleport:
  # How many seconds does the player have to wait to use the spawn command
  # again when the player moved during teleport time? (bypass permission: setthespawn.bypass.spawndelay)
  # Move includes damage, jump and any type of move.
  spawn-command-delay-after-move: 0

  # Player was moved while teleporting.
  move:
    enable: true

    # Message when the player moved.
    teleport-canceled: "&cTeleport cancelled, you can't move!"

    # While a player teleporting, the task will not cancel if this given and player moved.
    permission: setthespawn.bypass.movement

    # Play sound when a player moved while teleporting.
    play-sound:
      enable: false

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_ENDER_CHEST_CLOSE, 8, 1

    # If the player moved during teleporting, would the player pay for it or not?
    pay-if-moved:
      # Cost for moved during teleport
      cost: 0.0

      # The permission to bypass move pay
      permission: setthespawn.bypass.spawn.movedcost

  # Player was jump while teleporting.
  jump:
    enable: true

    # Message when the player jumped.
    teleport-canceled: "&cTeleport cancelled, you can't jump!"

    # While player teleporting, the task will not cancel if this given and player jumped.
    permission: setthespawn.bypass.jump

    # Play sound when a player jump while teleporting.
    play-sound:
      enable: false

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_WOODEN_DOOR_CLOSE

    # If the player jumped during teleporting, would the player pay for it or not?
    pay-if-jumped:
      # Cost for jumped during teleport
      cost: 0.0

      # The permission to bypass jump while teleporting.
      permission: setthespawn.bypass.spawn.jumpedcost

  # When the player is attacked somebody while teleporting.
  damage:
    enable: true

    # Message when the other player attacked.
    teleport-canceled: "&cTeleport cancelled, you are in combat!"

    # While player teleporting, the task will not cancel if this given and player got damage.
    permission: setthespawn.bypass.damage

    # Play sound when a player attacked someone while teleporting.
    play-sound:
      enable: false

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_LEVER_CLICK, 8, 1

    # If the player get damage during teleporting, would the player pay for it or not?
    pay-if-damage:
      # Cost for get damage during teleport
      cost: 0.0

      # The permission to bypass cancel teleport for getting damage.
      permission: setthespawn.bypass.spawn.damagecost

# When a player is being teleported, will plays an effect?
teleport-effect:
  # All effects:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
  # Usage: EFFECT_TYPE, duration
  #effect: ENDER_SIGNAL, 10

# Player sound when player teleported.
teleport-sound:
  # All sounds:
  # 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
  # 1.9+: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Usage: SOUND_TYPE, volume, pitch
  #sound: ENDERMAN_TELEPORT, 10, 1

# Launch firework when the player teleported to the spawn.
launch-firework:
  enable: false

  # This will fixes that issue when all the entities got damage after
  # player teleportation and launching a firework.
  # This calculates 15 radius around player to make sure the entities not get any damage.
  # If you have issues with this, then disable it.
  fix-entity-damage-after-teleportation: true

  # If true, the features below do not apply to it.
  random: true
  flicker: true
  trail: true

  # All firework types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
  type: STAR

  # Colors 0 - 255
  colors:
  - 229,0,0
  - 0,80,0
  - 0,0,103

  # Does the firework explode instantly?
  # If this enabled power setting are ignored.
  instant-explode: false

  # The power to launch the firework.
  power: 1

# Send title if:
title:
  # When you have started teleporting, a title will also be displayed.
  start-spawn:
    enable: false

    title: "&aTeleporting in"
    subtitle: "&6%seconds%&a seconds"

    # The title times to be displayed, stay and removing from the screen. (In ticks)
    # Usage: fadeIn, stay, fadeOut
    times: 10, 30, 60

  # When the player has teleported to the spawn and displays the title.
  end-spawn:
    enable: false

    title: "&3Teleport"
    subtitle: "&asuccess!"

    times: 10, 30, 60

  # When a player moves while teleporting.
  player-moved:
    enable: false

    title: "&cYou moved!"
    subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

  # When a player jump while teleporting.
  player-jump:
    enable: false

    title: "&cYou jumped!"
    subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

  # When player are attacked somebody while teleporting.
  player-damage:
    enable: false

    title: "&cA player was attacked!"
    subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

# If the player is in the void, will it teleports to the spawn?
void-on-spawn:
  enable: false

  # At that point, the player will be teleported to the spawn.
  # Example: 5 - so Y:5
  height: 0

  # If it is true, it does not hurt.
  # If it is false, it hurts.
  fall-distance: true

  # The list of disabled worlds where player shouldn't teleport to the set of spawn.
  disabled-worlds:
    # If enabled, the world names should target the set of spawn world.
    # For example, if you have set spawn in world1, and disabled world_nether,
    # players are not teleports to world1 spawn if falls into void.
    use-target-spawn-worlds: false

    list:
    #- end

  # When a player void, plays an effect?
  teleport-effect:
    # All effects:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
    #effect: ENDER_SIGNAL, 15

  # Message when the player has void fall and teleported to spawn.
  message: ""

# Teleport on command when the player teleported to spawn.
teleport-on-command:
  # Use player & console arguments for first.
  # You can use %player% & %world% placeholders.
  commands:
  #- "player: money"
  #- "player: kit"
  #- "console: eco take %player% 50"
  #- "console: money"

# Teleport to spawn if:
spawn-teleport:
  # the player joins the server?
  player-join: false

  # the player first joins the server?
  player-first-join: false

  # the player is died?
  respawn: false

# Spawn sign settings
spawn-sign:
  # Allows you to create and use the spawn sign.
  enable: true

  # Save signs automatically to a file when you place a sign?
  save-sign-data: false

  # If the player does not have permission to create a sign.
  no-permission-create-sign:
    # If it is true, it will break the sign.
    # If it is false, it does not break the sign.
    break-sign: false

    # If the above option "break-sign" is disabled, will using this.
    setline:
      lines:
      - "&cYou do not have"
      - "&cpermission"
      - "&cto create"
      - "&ca sign!"

  # If the spawn is not set up and what to write.
  no-spawn:
  - "&c[Spawn]"
  - "%text%"
  - "%text%"
  - "%text%"

  # If the spawn is set and what to write.
  spawn-created:
    lines:
    - "&9[Spawn]"
    - "%text%"
    - "%text%"
    - "%text%"

    everybody:
    - "&9[Spawn]"
    - "%all%"
    - "%text%"
    - "%text%"

    # If the world spawn is set and what to write.
    per-world:
      lines:
      - "&9[Spawn]"
      - "&6%world%"
      - "%text%"
      - "%text%"

      everybody:
      - "&9[Spawn]"
      - "%all%"
      - "%world%"
      - "%text%"

# Enable the gui setup?
enable-gui: false

# How many rows should the GUI have?
# This multiplies the specified number by 9, thus creating the GUI correctly.
gui-rows: 1

# What should the name of the GUI be?
gui-name: "&5Spawn settings"

# Close the GUI when a player clicks on an item and executed successfully?
close-gui-when-player-clicked-on-a-item: true

# All GUI items are here.
# How to add new item in GUI?: https://github.com/montlikadani/SetTheSpawn/wiki/How-to-add-new-item-to-GUI%3F%E2%80%8B
# Slot starts at 0 and end at 53 for a size 54 inventory.
items:
  slot-2:
    item: oak_sign
    name: "&3Setspawn"
    lore:
    - "&7------------"
    - "&aSet spawn command."
    - "&7------------"
    command: setspawn
  slot-4:
    item: ENDER_PEARL
    name: "&6Teleport"
    lore:
    - "&7------------"
    - "&aTeleport to the spawn."
    - "&7------------"
    command: spawn
  slot-6:
    item: bone
    name: "&4Delete spawn"
    lore:
    - "&7------------"
    - "&5Delete spawn location."
    - "&7------------"
    command: delspawn

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Download releases to \releases folder
# This only works if the "check-update" is true.
download-updates: true

# Log plugin messages into console.
logconsole: true

# DO NOT CHANGE THIS!
config-version: 12
